package:
  name: bioconductor-annotationforge
  version: 1.14.0
source:
  fn: AnnotationForge_1.14.0.tar.gz
  url: http://bioconductor.org/packages/release/bioc/src/contrib/AnnotationForge_1.14.0.tar.gz
  md5: f66ea49a5facc49bf0ffade5d9b78616
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - 'bioconductor-annotationdbi >=1.33.14'
    - 'bioconductor-biobase >=1.17.0'
    - 'bioconductor-biocgenerics >=0.15.10'
    - bioconductor-s4vectors
    - 'r >=2.7.0'
    - r-dbi
    - r-rsqlite
    - r-xml
  run:
    - 'bioconductor-annotationdbi >=1.33.14'
    - 'bioconductor-biobase >=1.17.0'
    - 'bioconductor-biocgenerics >=0.15.10'
    - bioconductor-s4vectors
    - 'r >=2.7.0'
    - r-dbi
    - r-rsqlite
    - r-xml
test:
  commands:
    - '$R -e "library(''AnnotationForge'')"'
about:
  home: http://bioconductor.org/packages/release/bioc/html/AnnotationForge.html
  license: Artistic-2.0
  summary: 'Provides code for generating Annotation packages and their databases.  Packages
    produced are intended to be used with AnnotationDbi.'
