package:
    name: umi_tools
    version: 0.0.8

source:
    fn: 0.0.8.tar.gz
    url: https://github.com/CGATOxford/UMI-tools/archive/0.0.8.tar.gz

build:
    number: 0
    skip: False

requirements:
    build:
        - gcc  # [linux]
        - llvm # [osx]
        - python
        - cython
        - pysam >=0.8.4
        - setuptools

    run:
        - libgcc # [linux]
        - htslib >=1.3
        - samtools >=1.3
        - bcftools ==1.3
        - python
        - cython >=0.19
        - pysam >=0.8.4
        - numpy >=1.7
        - pandas >=0.12.0
        - future 
        - setuptools
test:

    commands:
        - umi_tools --help
        - umi_tools extract --help
        - umi_tools dedup --help

about:
    home: https://github.com/CGATOxford/UMI-tools
    license: MIT
    summary: "umi_tools is a python module for dealing with Unique Molecular Identifiers (UMIs)/Random Molecular Tags (RMTs)"

