package:
  name: peddy
  version: "0.1.1"

source:
  fn: peddy-0.1.1.tar.gz
  url: https://pypi.python.org/packages/4c/8c/f93bef71f923852fcf8d96ac613353fb84494d355ca003d01f2cb0d6d42a/peddy-0.1.1.tar.gz
  md5: 53f037297cf05e0c0175854e54e5c86b

build:
  number: 0
  skip: True # [not py27]

requirements:
  build:
    - python
    - setuptools
    - networkx
    - cyvcf2
    - numpy
  run:
    - python
    - networkx
    - cyvcf2
    - numpy

test:
  imports:
    - peddy
    - peddy.tests

about:
  home: https://github.com/brentp/peddy
  license: MIT License
  summary: 'pleasingly pythonic pedigree manipulation'
