after_failure:
  - echo "ProtoCI build failed!"

after_script:
  - echo "ProtoCI build was a:$BINSTAR_BUILD_RESULT"

after_success:
  - echo "ProtoCI build success."

before_script:
  - conda install -c psteinberg conda-build=1.20 protoci=0.0.41

engine:
  - python=2.7
  - python=3.4
  - python=3.5

env:
  - CONDA_BOOST=1.60 CONDA_NPY=110 CONDA_PERL=5.22.0

platform:
  - linux-64
  - osx-64

script:
  - protoci-difference-build recipes

install_channels:
  - defaults
  - r
  - bioconda

package: bioconda

user: bioconda

# suppress print of messages ending in \r (interactive ones)
iotimeout: 200
