after_failure:
  - echo "ProtoCI build failed!"

after_script:
  - echo "ProtoCI build was a: $BINSTAR_BUILD_RESULT"

after_success:
  - echo "ProtoCI build success."

before_script:
  - mkdir conda_tmp
  # avoid conflict with conda or conda-build dirs if already there
  - git clone --branch 1.20.0 https://github.com/conda/conda-build conda_tmp/conda-build
  - git clone --branch 4.0.5 https://github.com/conda/conda conda_tmp/conda
  - conda install -c psteinberg protoci=0.0.41

engine:
  - python=2.7
  - python=3.4
  - python=3.5

env:
  - CONDA_BOOST=1.60 CONDA_NPY=110 CONDA_PERL=5.22.0

platform:
  - linux-64
#  - osx-64

script:
  # use updated conda
  - export PYTHONPATH=$PYTHONPATH:./conda_tmp/conda-build:./conda_tmp/conda
  - protoci-difference-build recipes

install_channels:
  - defaults
  - r
  - bioconda

package: bioconda

user: bioconda

# suppress print of messages ending in \r (interactive ones)
iotimeout: 200
