package:
  name: bioconductor-biocparallel
  version: 1.6.0
source:
  fn: BiocParallel_1.6.0.tar.gz
  url: http://bioconductor.org/packages/release/bioc/src/contrib/BiocParallel_1.6.0.tar.gz
  md5: 733497f793cd432b061b3d06038b5d96
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - r
    - r-futile.logger
    - r-snow
  run:
    - r
    - r-futile.logger
    - r-snow
test:
  commands:
    - '$R -e "library(''BiocParallel'')"'
about:
  home: http://bioconductor.org/packages/release/bioc/html/BiocParallel.html
  license: 'GPL-2 | GPL-3'
  summary: 'This package provides modified versions and novel implementation of functions
    for parallel evaluation, tailored to use with Bioconductor objects.'
