package:
  name: r-dendextend
  version: "1.2.0"

source:
  fn: dendextend_1.2.0.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/dendextend_1.2.0.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/dendextend/dendextend_1.2.0.tar.gz

build:
  number: 0

  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: dendextendRcpp (>= 0.5.0), knitr, testthat, colorspace, ggplot2, plyr, ape, profdpm, microbenchmark, gplots, NMF, d3heatmap, dynamicTreeCut, pvclust, corrplot, DendSer, MASS, cluster, circlize (>= 0.2.5), covr
requirements:
  build:
    - r
    - r-magrittr >=1.0.1
    - r-whisker

  run:
    - r
    - r-magrittr >=1.0.1
    - r-whisker

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('dendextend')" # [not win]
    - "\"%R%\" -e \"library('dendextend')\"" # [win]

about:
  home: http://cran.r-project.org/package=dendextend, https://github.com/talgalili/dendextend/,
    http://www.r-statistics.com/tag/dendextend/, http://bioinformatics.oxfordjournals.org/content/early/2015/08/18/bioinformatics.btv428
  license: GPL-2 | GPL-3
  summary: Offers a set of functions for extending dendrogram objects in R, letting you visualize
    and compare trees of hierarchical clusterings. You can (1) Adjust a tree's graphical
    parameters - the color, size, type, etc of its branches, nodes and labels. (2) Visually
    and statistically compare different dendrograms to one another.
