package:
  name: gimmemotifs
  version: '0.9.0.4'

source:
  url: https://github.com/simonvh/gimmemotifs/releases/download/0.9.0.4/gimmemotifs-0.9.0.4.tar.gz
  fn: gimmemotifs-0.9.0.4.tar.gz
  md5: 632351d339b9a68752a4606ec4f1b149

build:
  number: 0
  skip: True # [not py27 or osx]

requirements:
  build:
    - python
    - numpy
    - scipy
    - matplotlib
    - kid
    - pyyaml
    - pybedtools
    - pymc
    - scikit-learn
    - lightning
    - moods
    - statsmodels

  run:
    - python
    - numpy
    - scipy
    - matplotlib
    - kid
    - pyyaml
    - pybedtools
    - pymc
    - scikit-learn
    - lightning
    - moods
    - ucsc-genepredtobed
    - statsmodels

test:
  imports:
    - gimmemotifs

  commands:
    - gimme --help

about:
  home: https://github.com/simonvh/gimmemotifs
  license: MIT
  summary: Motif prediction pipeline and various motif-related tools
