package:
  name: bioconductor-limma
  version: 3.26.9
source:
  fn: limma_3.26.9.tar.gz
  url: http://bioconductor.org/packages/release/bioc/src/contrib/limma_3.26.9.tar.gz
  md5: 335aa265eea1418f949a8de906d14b8f
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - 'r >=2.3.0'
  run:
    - 'r >=2.3.0'
test:
  commands:
    - '$R -e "library(''limma'')"'
about:
  home: http://bioconductor.org/packages/release/bioc/html/limma.html
  license: 'GPL (>=2)'
  summary: 'Data analysis, linear models and differential expression for microarray
    data.'
