package:
  name: bioconductor-annotationdbi
  version: 1.32.3
source:
  fn: AnnotationDbi_1.32.3.tar.gz
  url: http://bioconductor.org/packages/release/bioc/src/contrib/AnnotationDbi_1.32.3.tar.gz
  md5: f1d5c71bbdaaa0a9c224a4df0a5af4f8
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - 'bioconductor-biobase >=1.17.0'
    - 'bioconductor-biocgenerics >=0.15.10'
    - bioconductor-iranges
    - bioconductor-s4vectors
    - 'r >=2.7.0'
    - r-dbi
    - r-rsqlite
  run:
    - 'bioconductor-biobase >=1.17.0'
    - 'bioconductor-biocgenerics >=0.15.10'
    - bioconductor-iranges
    - bioconductor-s4vectors
    - 'r >=2.7.0'
    - r-dbi
    - r-rsqlite
test:
  commands:
    - '$R -e "library(''AnnotationDbi'')"'
about:
  home: http://bioconductor.org/packages/release/bioc/html/AnnotationDbi.html
  license: Artistic-2.0
  summary: 'Provides user interface and database connection code for annotation data
    packages using SQLite data storage.'
