package:
    name: "ucsc-overlapselect"
    version: "332"
source:
    url: "http://hgdownload.cse.ucsc.edu/admin/exe/userApps.v332.src.tgz"          # [linux]
    fn: "userApps.src.tgz"                                                                     # [linux]
    md5: "8c2663c7bd302a77cdf52b2e9e85e2cd"                                                    # [linux]
    patches:                                                                                   # [linux]
        - "include.patch"                                                                      # [linux]

    url: "http://hgdownload.cse.ucsc.edu/admin/exe/macOSX.x86_64/overlapSelect"                    # [osx]
    fn: "overlapSelect"                                                                            # [osx]

build:                                                                                       # [osx]
    script: "mkdir -p $PREFIX/bin; cp overlapSelect $PREFIX/bin; chmod +x $PREFIX/bin/overlapSelect" # [osx]

requirements:
    build:
        - libpng                                                    # [linux]
        - mysql                                                     # [linux]
        - zlib                                                      # [linux]
        - openssl                                                   # [linux]
        - gcc

    run:                                                            # [linux]
        - libpng                                                    # [linux]
        - mysql                                                     # [linux]
        - zlib                                                      # [linux]
        - openssl                                                   # [linux]
        - libgcc

test:
    commands:
        # just check for existence, because the individual programs have no unified behavior
        - which overlapSelect

about:
    home: "http://hgdownload.cse.ucsc.edu/admin/exe/"
    license: "varies; see http://genome.ucsc.edu/license"
    summary: "
Select records based on overlapping chromosome ranges.  The ranges are
specified in the selectFile, with each block specifying a range.
Records are copied from the inFile to outFile based on the selection
criteria.  Selection is based on blocks or exons rather than entire
range.
"
