package:
  name: bioepic
  version: "0.0.6"

source:
  fn: bioepic-0.0.6.tar.gz
  url: https://pypi.python.org/packages/b2/fb/449b591e9a84c89a966e66cca01febdb305ed4dcedfee73dcce96fe4c46b/bioepic-0.0.6.tar.gz
  md5: bf096cd4486d5e60a32b368b24c66f46
#  patches:
   # List any patch files here
   # - fix.patch

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - scipy
    - pandas
    - numpy
    - natsort
    - joblib
    - docopt
    - pyfaidx
    - functools32 # [py27]

  run:
    - python
    - scipy
    - pandas
    - numpy
    - natsort
    - joblib
    - docopt
    - pyfaidx
    - functools32 # [py27]
    - bedtools

test:
  # Python imports
  imports:
    - epic
    - epic.config
    - epic.pool
    - epic.pool.index
    - epic.pool.merge
    - epic.pool.post_process
    - epic.run
    - epic.scripts
    - epic.statistics
    - epic.utils
    - epic.windows
    - epic.windows.cluster
    - epic.windows.count
    - tests
    - tests.windows

  commands:
    - epic -h

about:
  home: http://github.com/endrebak/epic
  license: GNU General Public License v3 (GPLv3)
  summary: 'Chip-Seq broad peak/domain finder.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
