package:
  name: vcfanno
  version: '0.0.11'

source:
  fn: vcfanno_0.0.11-beta_darwin_amd64.zip # [osx]
  url: https://github.com/brentp/vcfanno/releases/download/v0.0.11-beta/vcfanno_0.0.11-beta_darwin_amd64.zip # [osx]
  fn: vcfanno_0.0.11-beta_linux_amd64.tar.gz # [linux64]
  url: https://github.com/brentp/vcfanno/releases/download/v0.0.11-beta/vcfanno_0.0.11-beta_linux_amd64.tar.gz # [linux64]

build:
  number: 0

requirements:

test:
  commands:
    - vcfanno

about:
  home: https://github.com/brentp/vcfanno
  license: MIT
  summary: annotate a VCF with other VCFs/BEDs/tabixed files
