package:
  name: toil
  version: '3.2.0a2'

source:
  fn: toil-1c70e746.tar.gz
  url: https://github.com/guillermo-carrasco/toil/archive/1c70e746.tar.gz

build:
  number: 0
  skip: True # [not py27]

requirements:
  build:
    - python
    - setuptools
    - bd2k-python-lib
    - psutil
    - cgcloud-lib
    - boto
    - azure
    - cwltool
    # Packages to add -- Google and encryption support
    #- gcs-oauth2-boto-plugin
    #- pynacl

  run:
    - python
    - bd2k-python-lib
    - psutil
    - cgcloud-lib
    - boto
    - azure
    - cwltool
    # Packages to add -- Google and encryption support
    #- gcs-oauth2-boto-plugin
    #- pynacl

test:
  commands:
    - toil --help
    - cwltoil --help

about:
  home: https://github.com/BD2KGenomics/toil
  license: Apache 2.0
  summary: A scalable, efficient, cross-platform and easy-to-use workflow engine in pure Python
