package:
  name: scrm
  version: 1.6.1

source:
  fn:  scrm-src.tar.gz
  url: https://github.com/scrm/scrm/releases/download/v1.6.1/scrm-src.tar.gz
  md5: 6692b4db0c150e421a996240a3ea1d4d 

test:
  commands:
    - scrm 2 1 -T > /dev/null

about:
  home: https://scrm.github.io/
  summary: A coalescent simulator for genome-scale sequences
  license: GNU General Public License v3 or later (GPLv3+)
