package:
  name: cnvkit
  version: '0.7.11'

source:
  fn: v0.7.11.tar.gz
  url: https://github.com/etal/cnvkit/archive/v0.7.11.tar.gz

build:
  number: 0
  skip: False

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - atlas # [not osx]
    - numpy
    - scipy
    - pandas
    - matplotlib
    - biopython
    - reportlab
    - pysam >=0.8
    - pyvcf
    - r-pscbs
    - r-cghflasso
    - pyfaidx

test:
  imports:
    - cnvlib
  commands:
    - cnvkit.py -h

about:
  home: https://github.com/etal/cnvkit
  license: Apache License 2.0
  summary: Copy number variant detection from targeted DNA sequencing
