package:
  name: pilon
  version: '1.17'

source:
  fn: pilon-1.17.jar
  url: https://github.com/broadinstitute/pilon/releases/download/v1.17/pilon-1.17.jar
  md5: b63b63d1baa67a9d8c46bedea7ef9a4a

build:
  number: 0

requirements:
  run:
    - java-jdk

test:
  commands:
    - pilon --help | grep  'Usage' > /dev/null

about:
  home: https://github.com/broadinstitute/pilon/
  license: GPLv2
  summary: Pilon is an automated genome assembly improvement and variant detection tool.
