package:
  name: bioconductor-genefilter
  version: 1.52.1
source:
  fn: genefilter_1.52.1.tar.gz
  url: http://bioconductor.org/packages/release/bioc/src/contrib/genefilter_1.52.1.tar.gz
  md5: f0eed7c67eed467cccd0e1bac8c9764b
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - gcc
    - bioconductor-annotate
    - bioconductor-annotationdbi
    - bioconductor-biobase
    - r
  run:
    - libgcc
    - bioconductor-annotate
    - bioconductor-annotationdbi
    - bioconductor-biobase
    - r
test:
  commands:
    - '$R -e "library(''genefilter'')"'
about:
  home: http://bioconductor.org/packages/release/bioc/html/genefilter.html
  license: Artistic-2.0
  summary: 'Some basic functions for filtering genes'
