package:
  name: sambamba
  version: '0.6.1'

source:
  fn: sambamba_v0.6.1.tar.bz2
  url: https://github.com/lomereiter/sambamba/releases/download/v0.6.1/sambamba_v0.6.1_linux.tar.bz2 # [linux]
  url: https://github.com/lomereiter/sambamba/releases/download/v0.6.1/sambamba_v0.6.1_osx.tar.bz2 # [osx]

build:
  number: 0

requirements:
  build:
  run:
    - samtools # required for mpileup
    - bcftools # required for mpileup

test:
  commands:
    - sambamba view

about:
  home: https://github.com/lomereiter/sambamba
  license: GPLv2
  summary: Tools for working with SAM/BAM data
