package:
  name: inheritance
  version: 0.0.7

source:
  fn: inheritance-0.0.7.tar.gz
  url: https://pypi.python.org/packages/e4/e4/2bea3b57dd927da5e447f0b60c48f1f164e0c868c9cdc7a62f4b329083b1/inheritance-0.0.7.tar.gz
  md5: cdffd8775f3b1ed8b4e1238d3d793e71

build:
  number: 0
  skip: False

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - inheritance

about:
  home: https://github.com/brentp/inheritance
  summary: inheritance models for mendelian diseases
  license: MIT
