package:
  name: stack
  version: '1.1.2'

source:
  fn: v1.1.2.zip
  url: https://github.com/commercialhaskell/stack/archive/v1.1.2.zip

build:
  number: 0
  skip: 

test:
  commands:
    - stack --help

about:
  home: www.haskellstack.org/
  license: BSD3-like
  license_file: LICENSE
  summary: Stack is a cross-platform program for developing Haskell projects.
