package:
  name: bioconductor-biostrings
  version: 2.40.0
source:
  fn: Biostrings_2.40.0.tar.gz
  url: http://bioconductor.org/packages/release/bioc/src/contrib/Biostrings_2.40.0.tar.gz
  md5: 68614590e21fa020042ad63da3d0a02b
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - 'bioconductor-biocgenerics >=0.15.6'
    - 'bioconductor-iranges >=2.5.27'
    - 'bioconductor-s4vectors >=0.9.48'
    - 'bioconductor-xvector >=0.11.6'
    - 'r >=2.8.0'
  run:
    - 'bioconductor-biocgenerics >=0.15.6'
    - 'bioconductor-iranges >=2.5.27'
    - 'bioconductor-s4vectors >=0.9.48'
    - 'bioconductor-xvector >=0.11.6'
    - 'r >=2.8.0'
test:
  commands:
    - '$R -e "library(''Biostrings'')"'
about:
  home: http://bioconductor.org/packages/release/bioc/html/Biostrings.html
  license: Artistic-2.0
  summary: 'Memory efficient string containers, string matching algorithms, and other
    utilities, for fast manipulation of large biological sequences or sets of sequences.'
