package:
  name: ribotaper
  version: 1.3.1

source:
  fn: RiboTaper_Version_1.3.1.tar.gz
  url: https://ohlerlab.mdc-berlin.de/files/RiboTaper/RiboTaper_Version_1.3.1.tar.gz

build:
  skip: True  # [not linux]
  number: 0

requirements:
  build:
    - bedtools ==2.17.0
    - samtools
    - r-iterators
    - r-foreach
    - r-domc
    - r-ade4
    - r-seqinr
    - r-multitaper
    - r-xnomial
  run:
    - bedtools ==2.17.0
    - samtools
    - r-iterators
    - r-foreach
    - r-domc
    - r-ade4
    - r-seqinr
    - r-multitaper
    - r-xnomial

test:
  commands:
    - Ribotaper.sh 2>&1  | grep Usage > /dev/null
    - create_annotations_files.bash 2>&1  | grep Usage > /dev/null
    - create_metaplots.bash 2>&1  | grep Usage > /dev/null

about:
  home: https://ohlerlab.mdc-berlin.de/software/RiboTaper_126/
  license: GPL
  summary: 'RiboTaper is a new analysis pipeline for
  Ribosome Profiling (Ribo-seq) experiments,
  which exploits the triplet periodicity of
  ribosomal footprints to call translated regions.'
