package:
  name: bioconductor-gagedata
  version: 2.8.0
source:
  fn: gageData_2.8.0.tar.gz
  url: http://bioconductor.org/packages/release/data/experiment/src/contrib/gageData_2.8.0.tar.gz
  md5: b04d219020dc8c8b1850cb2b12df1547
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - 'r >=2.10'
  run:
    - 'r >=2.10'
test:
  commands:
    - '$R -e "library(''gageData'')"'
about:
  home: http://bioconductor.org/packages/release/data/experiment/html/gageData.html
  license: 'GPL (>=2.0)'
  summary: 'This is a supportive data package for the software package, gage. However,
    the data supplied here are also useful for gene set or pathway analysis or microarray
    data analysis in general. In this package, we provide two demo microarray dataset:
    GSE16873 (a breast cancer dataset from GEO) and BMP6 (originally published as
    an demo dataset for GAGE, also registered as GSE13604 in GEO). This package also
    includes commonly used gene set data based on KEGG pathways and GO terms for major
    research species, including human, mouse, rat and budding yeast. Mapping data
    between common gene IDs for budding yeast are also included.'
