package:
  name: wine
  version: 1.8.1

build:
  number: 0
  skip: False

source:
  fn: wine-1.8.1.tar.bz2
  url: https://dl.winehq.org/wine/source/1.8/wine-1.8.1.tar.bz2
  sha256: 149ad3daaf8593b36c5c061285df0ec2a25e20ea48c61323be91088c4d22ca97

requirements:
  build:
  run:

about:
  home: https://www.winehq.org/
  license: GPL
  summary: Wine Is Not an Emulator
test:
  commands:
    - wine --help
