package:
  name: deeptools
  version: '2.2.4'

source:
  fn: deepTools-2.2.4.tar.gz
  url: https://pypi.python.org/packages/b7/49/3ca95fe0737530274a3170de16d915acd8dfe6559fe8be1394a11779a258/deepTools-2.2.4.tar.gz
  md5: 2fc03daf386dadd7df66d769d66b0cb2

build:
  number: 0
  skip: True # [not py27]

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.8.0
    - scipy >=0.17.0
    - matplotlib >=1.4.0
    - pysam >=0.8.2
    - bx-python >=0.7.2
  run:
    - python
    - pybigwig >=0.2.3
    - numpy >=1.8.0
    - scipy >=0.17.0
    - matplotlib >=1.4.0
    - pysam >=0.8.2
    - bx-python >=0.7.2

test:
  imports:
    - deeptools

  commands:
    - bamCompare --version

about:
  home: https://github.com/fidelram/deepTools
  license: GPL3
  summary: A set of user-friendly tools for normalization and visualzation of deep-sequencing data
