package:
  name: samtools
  version: "1.3.1"

build:
  number: 0
  skip: False

source:
  fn: samtools-1.3.1.tar.bz2
  url: https://github.com/samtools/samtools/releases/download/1.3.1/samtools-1.3.1.tar.bz2
  md5: a7471aa5a1eb7fc9cc4c6491d73c2d88

requirements:
  build:
  - ncurses {{CONDA_NCURSES}}*
  - zlib
  run:
  - ncurses {{CONDA_NCURSES}}*
  - zlib

about:
  home: https://github.com/samtools/samtools
  license: MIT
  summary: Tools for dealing with SAM, BAM and CRAM files
test:
  commands:
    - samtools --help
