package:
  name: bioconductor-affyio
  version: 1.42.0
source:
  fn: affyio_1.42.0.tar.gz
  url: https://bioarchive.galaxyproject.org/affyio_1.42.0.tar.gz
  md5: 3d7a7f037fe7e1a312b4bb80329d05e4
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-zlibbioc
    - 'r >=2.6.0'
  run:
    - bioconductor-zlibbioc
    - 'r >=2.6.0'
test:
  commands:
    - '$R -e "library(''affyio'')"'
about:
  home: http://bioconductor.org/packages/release/bioc/html/affyio.html
  license: 'LGPL (>= 2)'
  summary: 'Routines for parsing Affymetrix data files based upon file format information.
    Primary focus is on accessing the CEL and CDF file formats.'
