package:
  name: bioconductor-biocinstaller
  version: 1.22.1
source:
  fn: BiocInstaller_1.22.1.tar.gz
  url: http://bioconductor.org/packages/release/bioc/src/contrib/BiocInstaller_1.22.1.tar.gz
  md5: 2655fe7e7e95ae445a5df04912af6b0d
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - 'r >=3.3.0'
  run:
    - 'r >=3.3.0'
test:
  commands:
    - '$R -e "library(''BiocInstaller'')"'
about:
  home: http://bioconductor.org/packages/release/bioc/html/BiocInstaller.html
  license: Artistic-2.0
  summary: 'This package is used to install and update Bioconductor, CRAN, and (some)
    github packages.'
