package:
  name: bioconductor-rbgl
  version: 1.46.0
source:
  fn: RBGL_1.46.0.tar.gz
  url: https://bioarchive.galaxyproject.org/RBGL_1.46.0.tar.gz
  md5: 011d5620fa8feab9fbd8222916e100f7
build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-graph
    - r
  run:
    - bioconductor-graph
    - r
test:
  commands:
    - '$R -e "library(''RBGL'')"'
about:
  home: http://bioconductor.org/packages/release/bioc/html/RBGL.html
  license: Artistic-2.0
  summary: 'A fairly extensive and comprehensive interface to the graph algorithms
    contained in the BOOST library.'
