package:
  name: cyvcf2
  version: '0.3.0'

source:
  fn: cyvcf2-0.3.0.tar.gz
  url: https://pypi.python.org/packages/ed/9a/fc22c3b1fe701e12e5fceb45b242c181d3c1cd912b704bd3ef342f0cc7b4/cyvcf2-0.3.0.tar.gz
  md5: 168acce8d1cb5c43b8d2e5b1bdc43ffd

build:
  number: 0
  skip: False

requirements:
  build:
    - python
    - setuptools
    - cython
    - numpy

  run:
    - python
    - numpy
    - matplotlib
    - seaborn
    - pandas

test:
  imports:
    - cyvcf2

about:
  home: https://github.com/brentp/cyvcf2
  summary: A cython wrapper around htslib built for fast parsing of Variant Call Format (VCF) files
  license: MIT
