package:
  name: bioconductor-biocstyle
  version: 2.0.0
source:
  fn: BiocStyle_2.0.0.tar.gz
  url: http://bioconductor.org/packages/release/bioc/src/contrib/BiocStyle_2.0.0.tar.gz
  md5: 3b75edc7b31aa6a865ff90c7f0ddd884
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - r
  run:
    - r
test:
  commands:
    - '$R -e "library(''BiocStyle'')"'
about:
  home: http://bioconductor.org/packages/release/bioc/html/BiocStyle.html
  license: Artistic-2.0
  summary: 'Provides standard formatting styles for Bioconductor PDF and HTML documents.
    Package vignettes illustrate use and functionality.'
