build:
  number: 3
  # XXX OSX currently failing due to problem with bundled shared libraries
  skip: True # [osx]
  string: boost{{CONDA_BOOST}}_{{PKG_BUILDNUM}}

about:
    home: https://github.com/COMBINE-lab/salmon
    license: GPLv3
    summary: Highly-accurate & wicked fast transcript-level quantification from RNA-seq reads using lightweight alignments
package:
    name: salmon
    version: 0.6.0
source:
  fn: SalmonBeta-0.6.0_OSX_10.11.tar.gz # [osx]
  url: https://github.com/COMBINE-lab/salmon/releases/download/v0.6.0/SalmonBeta-0.6.0_OSX_10.11.tar.gz # [osx]
  fn: salmon-v0.6.0.tar.gz # [linux]
  url: https://github.com/COMBINE-lab/salmon/archive/v0.6.0.tar.gz # [linux]
requirements:
  build:
    - boost {{CONDA_BOOST}}*
    - gcc # [linux]
    - llvm # [osx]
    - cmake
    - tbb
    - zlib
  run:
    - boost {{CONDA_BOOST}}*
    - tbb
    - libgcc
    - zlib
test:
    commands:
      - salmon --help
