package:
  name: ghc
  version: 8.0.1

source:
  fn: ghc-8.0.1-x86_64-deb8-linux.tar.xz # [linux64]
  url: http://downloads.haskell.org/~ghc/8.0.1/ghc-8.0.1-x86_64-deb8-linux.tar.xz # [linux64]
  md5: 08712c37398dd3f31706b279b1c73dc3 # [linux64]

build:
  number: 0
  skip: True # [osx]

requirements:
  build:
    - gmp
    - ncurses
  run:
    - gmp
    - ncurses
test:
  commands:
    - export GHC_LIBS_PATH=${PREFIX}/lib/ghc-8.0.1/
#array-0.5.1.1	     ghci-8.0.1		  pretty-1.1.3.3
#base-4.9.0.0	     ghci-usage.txt	  process-1.4.2.0
#bin		     ghc-prim-0.5.0.0	  
#binary-0.8.3.0	     ghc-usage.txt	  
#bytestring-0.10.8.1  haskeline-0.7.2.3	  template-haskell-2.11.0.0
#Cabal-1.24.0.0	     hoopl-3.10.2.1	  template-hsc.h
#containers-0.5.7.1   	  terminfo-0.4.0.2
#deepseq-1.4.2.0     		  time-1.6.0.1
#directory-1.2.6.2    		  transformers-0.5.2.0
#filepath-1.4.1.0     integer-gmp-1.0.0.1  unix-2.7.2.0
#ghc-8.0.1	     		  xhtml-3000.2.1
#ghc-boot-8.0.1	     
#ghc-boot-th-8.0.1    
    - cp ${PREFIX}/lib/ghc-8.0.1/*/*.so ${PREFIX}/lib/ghc-8.0.1/
    - export LD_LIBRARY_PATH=$GHC_LIBS_PATH/::$LD_LIBRARY_PATH
    - ghc-pkg recache 
    - ghc --help > /dev/null

about:
  home: https://www.haskell.org/ghc/
  license: BSD
  summary: "GHC is a state-of-the-art, open source, compiler and interactive environment for the functional language Haskell."
