about:
  home: 'https://github.com/dpryan79/PileOMeth'
  license: MIT
  summary: A (mostly) universal methylation extractor for BS-seq experiments.

package:
  name: pileometh
  version: 0.1.13

source:
  fn: 0.1.13.tar.gz
  url: https://github.com/dpryan79/PileOMeth/archive/0.1.13.tar.gz
  sha256: 9f70f847223ebf3bd074553928a4097fa9a6db5cdc5e7632b2062c96edb3c6a8

build:
  number: 1

requirements:
  build:
    - gcc   # [linux]
    - zlib
  run:
    - zlib

test:
  commands:
    - cd tests && python ./test.py
