about:
  home: https://github.com/chapmanb/gatk
  license: MIT
  summary: The core MIT-licensed Genome Analysis Toolkit (GATK) framework, free for all uses

package:
  name: gatk-framework
  version: '3.5.21'

build:
  number: 0
  skip: False

source:
  fn: gatk-framework-3.5-21.tar.gz
  url: https://github.com/chapmanb/gatk/releases/download/v3.5-21-framework/gatk-framework-3.5-21.tar.gz

requirements:
  run:
    - java-jdk >=7,<8

test:
    commands:
      - gatk-framework --version
