package:
  name: vcf2db
  version: '2016.04.29'

build:
  number: 0
  skip: True # [not py27]
 
source:
  fn: vcf2db-ed7008a.tar.gz
  url: https://github.com/quinlan-lab/vcf2db/archive/ed7008a.tar.gz

requirements:
  build:
    - python
    - perl-threaded
    - nomkl # [unix]
    - snappy
    - python-snappy
    - sqlalchemy
    - cyvcf2
    - numpy
    - peddy
    - geneimpacts
  run:
    - python
    - nomkl # [unix]
    - snappy
    - python-snappy
    - sqlalchemy
    - cyvcf2
    - numpy
    - peddy
    - geneimpacts

test:
  commands:
    - vcf2db.py -h

about:
  home: https://github.com/quinlan-lab/vcf2db
  license: MIT
  summary: Create a gemini-compatible database from a VCF
